### ISSUE TITLE
Update user stories based on conversation with customer

### ISSUE THREAD

**Issue by Karolill** [olemagnusnorum/kundestyrt-prosjekt-gruppe-12#63]
Check bot the big user stories and the small ones. 

Should also consider:

- [x] Does #41 have anything to do with "Sykemelding" or only "Venter barn"
- [x] Can #46 be removed? Is it enough that NAV subscribes to information, so that it is uneccesary that the doctor sends information in this case?
- [x] Regarding #52, does it have anything to do with "Venter barn"? Is there any reason why NAV should respond to information in this case?
